apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-dex-oidc-configurator
  namespace: istio-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeflow-dex-oidc-configurator
  namespace: istio-system
rules:
  - apiGroups:
      - security.istio.io
    resources:
      - requestauthentications
    verbs:
      - get
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeflow-dex-oidc-configurator
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeflow-dex-oidc-configurator
subjects:
  - kind: ServiceAccount
    name: kubeflow-dex-oidc-configurator
    namespace: istio-system
