prometheus:
  server:
    baseURL: "http://localhost:80/prometheus"
    extraArgs:
      web.route-prefix: "/"
    podLabels: 
      app: prometheus-server
  kube-state-metrics:
    metricLabelsAllowlist:
    - pods=[*]
  extraScrapeConfigs: |
    - job_name: 'dcgm_exporter'
      static_configs:
        - targets: ['nvidia-dcgm-exporter.gmp-public:9400']
    - job_name: 'knative-serving'
      scrape_interval: 3s
      kubernetes_sd_configs: 
      - role: pod
      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_role, __meta_kubernetes_pod_container_port_name]
        regex: knative-serving;(controller|activator|autoscaler|webhook);metrics
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
    - job_name: queue-proxy
      scrape_interval: 3s
      kubernetes_sd_configs: 
      - role: pod
      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_pod_label_serving_knative_dev_revision, __meta_kubernetes_pod_container_port_name]
        regex: (.*);http-usermetric
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
    - job_name: 'vllm'
      scrape_interval: 3s
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_component, __meta_kubernetes_pod_container_port_name]
        regex: (.*);predictor;user-port
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
grafana:
  podLabels:
    app: grafana
  persistence:
    enabled: true
  grafana.ini:
    server:
      root_url: 'http://localhost:3000/grafana/'
      serve_from_sub_path: true
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://metric-prometheus-server.istio-system.svc.cluster.local
        access: proxy
        isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: grafana-dashboards