apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: tgi-mig-bnb
  namespace: admin-profile
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    containers:
    - args:
      - --model-id
      - /mnt/models/newjeans-finetuning-wngs4
      - --quantize
      - "bitsandbytes-nf4"
      image: ghcr.io/huggingface/text-generation-inference:2.0
      name: kserve-container
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        limits:
          cpu: "2"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          memory: 16Gi
          nvidia.com/gpu: "1"
      volumeMounts:
      - mountPath: /dev/shm
        name: shm
      - mountPath: /mnt/models
        name: model
    maxReplicas: 1
    minReplicas: 1
    volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 16Gi
      name: shm
    - persistentVolumeClaim:
        claimName: newjeans-finetuning-pvc-rwx
      name: model

---

kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: kserve-gateway
  namespace: istio-system
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: kserve-certificate

---

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: kserve-route
  namespace: istio-system
  labels:
    gateway: kserve-gateway
spec:
  parentRefs:
  - name: kserve-gateway
  hostnames:
  - "*.admin-profile.llmops-kiyoung01.com" # cloud domain으로 생성한 도메인 추가
  rules:
  - backendRefs:
    - name: istio-ingressgateway
      port: 80
