apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- ../../base

patchesStrategicMerge:
- patches/model-registry-deployment.yaml

# vars:
# - name: MYSQL_PORT
#   objref:
#     kind: ConfigMap
#     name: pipeline-install-config
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.dbPort
