apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- ../../base

patchesStrategicMerge:
- patches/model-registry-deployment.yaml

configMapGenerator:
- envs:
  - params.env
  name: model-registry-db-parameters
secretGenerator:
- envs:
  - secrets.env
  name: model-registry-db-secrets
generatorOptions:
  disableNameSuffixHash: true

vars:
- name: MYSQL_PORT
  objref:
    kind: ConfigMap
    name: model-registry-db-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.MYSQL_PORT
