apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../third-party/metacontroller/base
  - ../../base/installs/multi-user
  - ../../base/metadata/base
  - ../../base/metadata/options/istio
  - ../../third-party/argo/installs/cluster
  # - ../../third-party/mysql/base
  # - ../../third-party/mysql/options/istio
  # - ../../third-party/minio/base
  # - ../../third-party/minio/options/istio

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  application-crd-id: kubeflow-pipelines

# !!! If you want to customize the namespace,
# please also update base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
namespace: kubeflow

patchesStrategicMerge:
  - cache-server.yaml
  - pipeline-install-config.yaml
patches:
  - path: aws-configuration-pipeline-patch.yaml
  - path: aws-configuration-pipeline-ui-patch.yaml

# Used by Kustomize
configMapGenerator:
  - name: workflow-controller-configmap
    behavior: replace
    files:
      - config
  - name: ml-pipeline-ui-configmap
    behavior: replace
    files:
      - viewer-pod-template.json
secretGenerator:
  - name: mysql-secret
    env: secret.env
    behavior: merge
generatorOptions:
  disableNameSuffixHash: true