apiVersion: v1
kind: Pod
metadata:
  name: gradio
  namespace: admin-profile
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    app.kubernetes.io/name: gradio
spec:
  containers:
  - name: gradio
    image: python:3.11
    command: ["/bin/bash", "-c"]
    args:
    - |
      PIP_DISABLE_PIP_VERSION_CHECK=1 python3 -m pip install --quiet \
        --no-warn-script-location gradio openai
      python3 /mnt/gradio/app.py
    env:
    - name: GRADIO_SERVER_NAME
      value: "0.0.0.0"
    - name: INFERENCE_SERVICE
      value: http://newjeans.admin-profile.svc.cluster.local
    - name: MODEL_NAME
      value: Meta-Llama-3-Instruct
    ports:
      - containerPort: 7860
        name: gradio-web
    volumeMounts:
      - name: application
        mountPath: /mnt/gradio
    resources: {}
  volumes:
    - name: application
      configMap:
        name: gradio-app
        defaultMode: 0555
        items:
        - key: app.py
          path: app.py
---
apiVersion: v1
kind: Service
metadata:
  name: gradio
  namespace: admin-profile
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: gradio
  ports:
  - name: gradio-web
    protocol: TCP
    port: 80
    targetPort: gradio-web