apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../oauth2-proxy
- ingress.yaml

patches:
- path: istio-ingressgateway-service.yaml
  target:
    version: v1
    kind: Service
    name: istio-ingressgateway
    namespace: istio-system
