apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: https://kubeflow.<<domain>>/dex # cloud domain으로 생성한 도메인 추가(ex: example.com)
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    connectors:
    - type: google
      id: google
      name: Google
      config:
        clientID: <<client_id>>
        clientSecret: <<client_secret>>
        redirectURI: https://kubeflow.<<domain>>/dex/callback
    enablePasswordDB: true
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/authservice/oidc/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET