apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "metric.fullname" . }}-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "metric.fullname" . }}-gateway
  http:
  - name: grafana
    match:
    - uri:
        exact: /grafana
    - uri:
        prefix: /grafana
    - uri:
        prefix: /grafana/
    route:
    - destination:
        host: {{ .Values.grafana.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
  - name: prometheus
    match:
    - uri:
        exact: /prometheus
    - uri:
        prefix: /prometheus/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: {{ .Values.prometheus.server.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
  - name: jaeger
    match:
    - uri:
        exact: /jaeger
    - uri:
        prefix: /jaeger/
    - uri:
        prefix: /js
    - uri:
        prefix: /static
    route:
    - destination:
        host: {{ .Values.jaeger.fullnameOverride }}-query.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 16686