apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubeflow-dex-oidc-configurator
  namespace: istio-system
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels: {}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: kubeflow-dex-oidc-configurator
          containers:
            - image: docker.io/curlimages/curl
              name: kubeflow-dex-oidc-configurator
              command:
                - /script.sh
              envFrom:
                - configMapRef:
                    name: kubeflow-dex-oidc-configurator-envs
              volumeMounts:
                - mountPath: /script.sh
                  name: script
                  subPath: script.sh
              resources: {}
          volumes:
            - name: script
              configMap:
                name: kubeflow-dex-oidc-configurator-script
                defaultMode: 0777
                items:
                  - key: script.sh
                    path: script.sh
