apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mlflow.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "mlflow.secretName" . }}
            - confiaMapRef:
                name: {{ include "mlflow.configMapName" . }}
          env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.artifactStore.region }}
            - name: ARTIFACT_STORE
              value: "s3://{{ .Values.artifactStore.bucket }}/mlflow"
          command: ["mlflow", "server"]
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - {{ .Values.mlflowPort | quote }}
            - "--default-artifact-root"
            - "$(ARTIFACT_STORE)"
            - "--backend-store-uri"
            - "mysql+pymysql://$(DB_USER):$(DB_PW)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.mlflowPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.mlflowPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
