kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "mlflow.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      options:
        ## terraform으로 생성했던 managed SSL certification
        networking.gke.io/pre-shared-certs: {{ .Values.certificate }}

---

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "mlflow.fullname" . }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    gateway: {{ include "mlflow.fullname" . }}-gateway
spec:
  parentRefs:
  - name: {{ include "mlflow.fullname" . }}-gateway
  hostnames:
  - {{ include "mlflow.fullname" . }}.{{ .Values.dns }}
  rules:
  - backendRefs:
    - name: {{ include "mlflow.fullname" . }}
      port: {{ .Values.service.port }}
