apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.secret.contents.backendStore }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
