apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
spec:
  gateways:
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: {{ .Values.httpRelativePath }}
    route:
    - destination:
        host: {{ template "common.names.fullname" . }}.{{ include "common.names.namespace" . }}.svc.cluster.local
        port:
          number: {{ coalesce .Values.service.ports.http .Values.service.port }}
